version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "piggybank-s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p0csxzxfadjw"
s3_prefix = "piggybank-s3"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
